language: python
env:
  - REQUIREMENTS=true
  - REQUIREMENTS=false
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"
before_install:
  - export _PIP32=''
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]] ; then export _PIP32='<8'; fi
  - pip install --upgrade pip${_PIP32}
# command to install dependencies
install:
  - if [[ $REQUIREMENTS == true ]] ; then pip install -r requirements.txt ; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.2' ]] ; then pip install coverage==3.7.1; fi
  - pip install coveralls pytest pytest-cov coverage codecov
  - pip install -e .
  - if [[ ! $TRAVIS_PYTHON_VERSION == 'pypy' ]] ; then pip install regex; fi
# command to run tests
script: py.test
sudo: false
after_success:
  - coveralls
  - codecov
